# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:00:24+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from pydantic import EmailStr, conint, constr

from models import (
    EntryInfoResponse,
    ErrorResponse,
    InfoResponse,
    LinksResponse,
    ReferenceResponseMany,
    ReferenceResponseOne,
    StructureResponseMany,
    StructureResponseOne,
)

app = MCPProxy(
    description='The [Open Databases Integration for Materials Design (OPTIMADE) consortium](https://www.optimade.org/) aims to make materials databases interoperational by developing a common REST API.\n\nThis specification is generated using [`optimade-python-tools`](https://github.com/Materials-Consortia/optimade-python-tools/tree/v0.16.0) v0.16.0.',
    title='OPTIMADE API',
    version='1.1.0~develop',
    servers=[{'url': 'http://optimade.local'}],
)


@app.get('/info', tags=['info_retrieval'])
def get_info_info_get():
    """
    Get Info
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/info/{entry}', tags=['info_retrieval'])
def get_entry_info_info__entry__get(entry: str):
    """
    Get Entry Info
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/links',
    tags=[
        'info_retrieval',
        'link_retrieval',
        'reference_retrieval',
        'structure_info_management',
    ],
)
def get_links_links_get(
    filter: Optional[str] = '',
    response_format: Optional[str] = 'json',
    email_address: Optional[EmailStr] = '',
    response_fields: Optional[
        constr(pattern=r'([a-z_][a-z_0-9]*(,[a-z_][a-z_0-9]*)*)?')
    ] = '',
    sort: Optional[constr(pattern=r'([a-z_][a-z_0-9]*(,[a-z_][a-z_0-9]*)*)?')] = '',
    page_limit: Optional[conint(ge=0)] = 20,
    page_offset: Optional[conint(ge=0)] = 0,
    page_number: Optional[conint(ge=0)] = 0,
    page_cursor: Optional[conint(ge=0)] = 0,
    page_above: Optional[conint(ge=0)] = 0,
    page_below: Optional[conint(ge=0)] = 0,
    include: Optional[str] = 'references',
    api_hint: Optional[constr(pattern=r'(v[0-9]+(\.[0-9]+)?)?')] = '',
):
    """
    Get Links
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/references',
    tags=[
        'info_retrieval',
        'link_retrieval',
        'reference_retrieval',
        'structure_info_management',
    ],
)
def get_references_references_get(
    filter: Optional[str] = '',
    response_format: Optional[str] = 'json',
    email_address: Optional[EmailStr] = '',
    response_fields: Optional[
        constr(pattern=r'([a-z_][a-z_0-9]*(,[a-z_][a-z_0-9]*)*)?')
    ] = '',
    sort: Optional[constr(pattern=r'([a-z_][a-z_0-9]*(,[a-z_][a-z_0-9]*)*)?')] = '',
    page_limit: Optional[conint(ge=0)] = 20,
    page_offset: Optional[conint(ge=0)] = 0,
    page_number: Optional[conint(ge=0)] = 0,
    page_cursor: Optional[conint(ge=0)] = 0,
    page_above: Optional[conint(ge=0)] = 0,
    page_below: Optional[conint(ge=0)] = 0,
    include: Optional[str] = 'references',
    api_hint: Optional[constr(pattern=r'(v[0-9]+(\.[0-9]+)?)?')] = '',
):
    """
    Get References
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/references/{entry_id}', tags=['info_retrieval', 'reference_retrieval'])
def get_single_reference_references__entry_id__get(
    entry_id: str,
    response_format: Optional[str] = 'json',
    email_address: Optional[EmailStr] = '',
    response_fields: Optional[
        constr(pattern=r'([a-z_][a-z_0-9]*(,[a-z_][a-z_0-9]*)*)?')
    ] = '',
    include: Optional[str] = 'references',
    api_hint: Optional[constr(pattern=r'(v[0-9]+(\.[0-9]+)?)?')] = '',
):
    """
    Get Single Reference
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/structures',
    tags=[
        'info_retrieval',
        'link_retrieval',
        'reference_retrieval',
        'structure_info_management',
    ],
)
def get_structures_structures_get(
    filter: Optional[str] = '',
    response_format: Optional[str] = 'json',
    email_address: Optional[EmailStr] = '',
    response_fields: Optional[
        constr(pattern=r'([a-z_][a-z_0-9]*(,[a-z_][a-z_0-9]*)*)?')
    ] = '',
    sort: Optional[constr(pattern=r'([a-z_][a-z_0-9]*(,[a-z_][a-z_0-9]*)*)?')] = '',
    page_limit: Optional[conint(ge=0)] = 20,
    page_offset: Optional[conint(ge=0)] = 0,
    page_number: Optional[conint(ge=0)] = 0,
    page_cursor: Optional[conint(ge=0)] = 0,
    page_above: Optional[conint(ge=0)] = 0,
    page_below: Optional[conint(ge=0)] = 0,
    include: Optional[str] = 'references',
    api_hint: Optional[constr(pattern=r'(v[0-9]+(\.[0-9]+)?)?')] = '',
):
    """
    Get Structures
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/structures/{entry_id}',
    tags=['info_retrieval', 'structure_info_management', 'reference_retrieval'],
)
def get_single_structure_structures__entry_id__get(
    entry_id: str,
    response_format: Optional[str] = 'json',
    email_address: Optional[EmailStr] = '',
    response_fields: Optional[
        constr(pattern=r'([a-z_][a-z_0-9]*(,[a-z_][a-z_0-9]*)*)?')
    ] = '',
    include: Optional[str] = 'references',
    api_hint: Optional[constr(pattern=r'(v[0-9]+(\.[0-9]+)?)?')] = '',
):
    """
    Get Single Structure
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/versions',
    description=""" Respond with the text/csv representation for the served versions. """,
    tags=['info_retrieval'],
)
def get_versions_versions_get():
    """
    Get Versions
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
